// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0X_yCbrpaZjT7az34T38dJFwzGj1-miI',
    appId: '1:127378341349:web:01d456b4b1a23a1483430c',
    messagingSenderId: '127378341349',
    projectId: 'edri-ihub',
    authDomain: 'edri-ihub.firebaseapp.com',
    storageBucket: 'edri-ihub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVHUz3l3SX1YaJOQYUnlXBL7y6W6l-M3M',
    appId: '1:127378341349:android:d15d5d684f3722a283430c',
    messagingSenderId: '127378341349',
    projectId: 'edri-ihub',
    storageBucket: 'edri-ihub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmpKWjrtwIlxzrEdE6d9Vb4hYyoHZb_w',
    appId: '1:127378341349:ios:96dc433c9104c89383430c',
    messagingSenderId: '127378341349',
    projectId: 'edri-ihub',
    storageBucket: 'edri-ihub.appspot.com',
    iosClientId: '127378341349-jd3igqj2dkilbgb5b1r6drn5o9uojc9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.edri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmpKWjrtwIlxzrEdE6d9Vb4hYyoHZb_w',
    appId: '1:127378341349:ios:96dc433c9104c89383430c',
    messagingSenderId: '127378341349',
    projectId: 'edri-ihub',
    storageBucket: 'edri-ihub.appspot.com',
    iosClientId: '127378341349-jd3igqj2dkilbgb5b1r6drn5o9uojc9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.edri',
  );
}
